version: '3.1'
services:
  data-base:
    image: mysql
    container_name: post-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: mohamed
      MYSQL_PASSWORD: 123
    restart: always
  app-service:
    build:
      dockerfile: Dockerfile
    container_name: post-service
    ports:
      - '8080:8080'
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: mohamed
      MYSQL_PASSWORD: 123
      DATA_BASE_HOST: data-base
      DATA_BASE_PORT: 3306
    depends_on:
      - data-base



