apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-base-deployment
spec:
  selector:
    matchLabels:
      app: post-db
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
        - name: post-db
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_USER
              value: mohamed
            - name: MYSQL_PASSWORD
              value: '123'
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: data-base-service
spec:
  selector:
    app: post-db
  ports:
    - name: db
      port: 3306
      protocol: TCP
      targetPort: 3306


---
#apiVersion: v1
#kind: Service
#metadata:
#  name: data-base-service-node-port
#spec:
#  type: NodePort
#  selector:
#    app: post-db
#  ports:
#    - name: db-port
#      port: 3306
#      protocol: TCP
#      targetPort: 3306