apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
spec:
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: dev19med/post-service
          env:
            - name: DATA_BASE_HOST
              value: data-base-service
            - name: DATA_BASE_PORT
              value: '3306'
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_USER
              value: mohamed
            - name: MYSQL_PASSWORD
              value: '123'
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post
  ports:
    - name: post-service-port
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: data-base-service-node-port
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - name: post-app-node-port
      nodePort: 32050
      port: 8080
      protocol: TCP
      targetPort: 8080